[theme]
primaryColor="#E31B23"
backgroundColor="#0F2337"
secondaryBackgroundColor="#1B3548"
textColor="#FFFFFF"
base="dark"

[browser]
gatherUsageStats=false

[client]
showErrorDetails=false
toolbarMode="minimal"

[deprecation]
showfileUploaderEncoding=false

[global]
developmentMode=false

[ui]
hideStreamlitStyle=true
